### ISSUE TITLE
Value cleared if equal to placeholder

### ISSUE THREAD

**Issue by whiteatom** [tborychowski/formparams#1]
This is probably not a bug, but it's giving non-logical results, so I wanted to raise it. I love your plugin and use it in almost all my projects - this is the first time I've had an issue.

Why is this line of code in your plugin?

```
	// clear placeholder valus for IEs
	if ($el.data('changed') !== true && value === $el.attr('placeholder')) value = '';
```

In my current project, the client wants placeholders that are examples of what would be filled out. They have decided to use the most common entries they expect their clients to use (not my choice). Now - this line of code is is removing the client entries from the object created by your plug in. 

Based on the comment above it, I assume this is a hack for a stupid older version of IE, but can you confirm? could we wrap it in if(IE)?

**Comment by tborychowski** [comment]
Hi,
Wow, I haven't looked into this code for a long time! :-)
I moved since to sth like [this](https://github.com/tborychowski/github-browser/blob/master/app/util/form.js) - much more flexible and modern.

Yes, that is definitely hack for IE8 (AFAIR).
Theoretically, if you remove this line or add an `if (ie8)` check - it should work nicely.
